import React, { Component } from 'react';
import { connect } from "react-redux";
import { FormattedMessage } from 'react-intl';
import QuestionItem from './questionItem';

class Insurance extends Component {
    constructor(props) {
        super(props);
        this.state = {

        }
    }

    render() {

        return (
            <>
                <h3>Bảo hiểm</h3>
                <div className='question'>
                    <QuestionItem
                        question={'Bệnh viện và phòng khám trên BC có hỗ trợ thanh toán bảo hiểm y tế không?'}
                        answer={'<p>T&ugrave;y thuộc theo bệnh viện/ph&ograve;ng kh&aacute;m. Đối với từng b&aacute;c sĩ, phần th&ocirc;ng tin về c&aacute;c loại bảo hiểm hỗ trợ thanh to&aacute;n tại bệnh viện/ph&ograve;ng kh&aacute;m - nơi b&aacute;c sĩ c&oacute; lịch kh&aacute;m - xuất hiện ngay b&ecirc;n dưới lịch kh&aacute;m của b&aacute;c sĩ.&nbsp;</p><p>Lưu &yacute;: Bạn cần xem đ&uacute;ng ng&agrave;y kh&aacute;m của b&aacute;c sĩ để c&oacute; th&ocirc;ng tin về bảo hiểm ch&iacute;nh x&aacute;c, v&igrave; một b&aacute;c sĩ tr&ecirc;n hệ thống BookingCare c&oacute; thể kh&aacute;m ở c&aacute;c bệnh viện v&agrave; ph&ograve;ng kh&aacute;m kh&aacute;c nhau.</p><div id="eJOY__extension_root" class="eJOY__extension_root_class" style="all: unset;">&nbsp;</div>'}
                    />
                    <QuestionItem
                        question={'Bệnh viện và phòng khám ở trên BookingCare có bảo lãnh cho bảo hiểm tư nhân không?'} answer={'<p>T&ugrave;y thuộc theo bệnh viện/ph&ograve;ng kh&aacute;m. Th&ocirc;ng tin về bảo hiểm tư nh&acirc;n được bảo l&atilde;nh trực tiếp tại bệnh viện/ph&ograve;ng kh&aacute;m được xuất hiện ngay b&ecirc;n dưới lịch kh&aacute;m của b&aacute;c sĩ. Bạn c&oacute; thể tra cứu danh s&aacute;ch bảo hiểm bảo l&atilde;nh trực tiếp tại phần n&agrave;y.</p><p>Ngo&agrave;i ra, để biết được ch&iacute;nh x&aacute;c loại thẻ m&agrave; bạn đang sử dụng được bảo l&atilde;nh những danh mục n&agrave;o v&agrave; bao nhi&ecirc;u phần trăm, bạn cần mang thẻ bảo hiểm c&ugrave;ng giấy tờ t&ugrave;y th&acirc;n đến bệnh viện/ph&ograve;ng kh&aacute;m để được c&aacute;c bạn nh&acirc;n vi&ecirc;n y tế hướng dẫn. Bạn cũng c&oacute; thể chủ động gọi điện thoại l&ecirc;n c&ocirc;ng ty bảo hiểm để biết được th&ocirc;ng tin n&agrave;y.</p><div id="eJOY__extension_root" class="eJOY__extension_root_class" style="all: unset;">&nbsp;</div>'}
                    />
                    <QuestionItem
                        question={'Bệnh viện và phòng khám có áp dụng bảo hiểm vào Thứ Bảy và Chủ nhật không?'}
                        answer={'Tùy thuộc vào bệnh viện/phòng khám và tùy thuộc vào loại thẻ bảo hiểm y tế của bạn. Khi đi khám, bạn nên mang theo thẻ bảo hiểm và giấy tờ tùy thân để được nhân viên y tế hướng dẫn.'}
                    />
                    <QuestionItem
                        question={'Khám bệnh, chữa bệnh đúng tuyến là gì?'}
                        answer={'<p>6 trường hợp được coi l&agrave; kh&aacute;m chữa bệnh đ&uacute;ng tuyến:</p><ul><li>Người c&oacute; thẻ bảo hiểm y tế đăng k&yacute; kh&aacute;m chữa bệnh ban đầu tại cơ sở kh&aacute;m chữa bệnh tuyến x&atilde; hoặc tuyến huyện thực hiện kh&aacute;m chữa bệnh tại trạm y tế tuyến x&atilde; hoặc tuyến huyện trong c&ugrave;ng địa b&agrave;n tỉnh.</li><li>Người c&oacute; thẻ bảo hiểm y tế đăng k&yacute; kh&aacute;m chữa bệnh ban đầu tại cơ sở kh&aacute;m chữa bệnh tuyến x&atilde; chuyển tuyến đến bệnh viện huyện.</li><li>Người c&oacute; thẻ bảo hiểm y tế được bệnh viện tuyến huyện chuyển tuyến đến trung t&acirc;m chuy&ecirc;n khoa tuyến tỉnh hoặc bệnh viện đa khoa, bệnh viện chuy&ecirc;n khoa, viện chuy&ecirc;n khoa tuyến tỉnh c&ugrave;ng hạng hoặc hạng thấp hơn.</li><li>Đối với trường hợp cấp cứu: Người bệnh được cấp cứu tại bất kỳ cơ sở kh&aacute;m bệnh, chữa bệnh n&agrave;o. Sau giai đoạn điều trị cấp cứu, người bệnh được chuyển v&agrave;o điều trị nội tr&uacute; tại nơi đ&atilde; tiếp nhận cấp cứu người bệnh hoặc được chuyển đến cơ sở kh&aacute;m bệnh, chữa bệnh kh&aacute;c để tiếp tục điều trị theo y&ecirc;u cầu chuy&ecirc;n m&ocirc;n</li><li>Trường hợp người bệnh được chuyển tuyến kh&aacute;m chữa bệnh c&oacute; bệnh kh&aacute;c k&egrave;m theo, bệnh được ph&aacute;t hiện hoặc ph&aacute;t sinh ngo&agrave;i bệnh đ&atilde; ghi tr&ecirc;n giấy chuyển tuyến, cơ sở kh&aacute;m chữa bệnh nơi tiếp nhận người bệnh thực hiện việc kh&aacute;m chữa bệnh đối với c&aacute;c bệnh đ&oacute; trong phạm vi chuy&ecirc;n m&ocirc;n.</li><li>Trường hợp người tham gia bảo hiểm y tế đi c&ocirc;ng t&aacute;c, học tập, l&agrave;m việc lưu động hoặc tạm tr&uacute; dưới 12 th&aacute;ng tại địa phương kh&aacute;c th&igrave; được kh&aacute;m chữa bệnh tại cơ sở kh&aacute;m chữa bệnh tr&ecirc;n địa phương đ&oacute; tương đương với tuyến của cơ sở kh&aacute;m chữa bệnh ban đầu ghi tr&ecirc;n thẻ bảo hiểm y tế. Trường hợp địa phương đ&oacute; kh&ocirc;ng c&oacute; cơ sở y tế tương đương th&igrave; người tham gia bảo hiểm y tế được lựa chọn cơ sở kh&aacute;m bệnh, chữa bệnh kh&aacute;c c&oacute; tổ chức kh&aacute;m bệnh, chữa bệnh bảo hiểm y tế ban đầu.</li></ul><p><em>(Theo Th&ocirc;ng tư 40/2015/TT-BYT của Bộ Y tế)</em></p><p>&nbsp;</p><p>T&oacute;m lại,&nbsp;</p><ul><li>Trường hợp người bệnh kh&aacute;m chữa bệnh tại cơ sở đăng k&iacute; kh&aacute;m chữa bệnh ban đầu hoặc cơ sở tại tuyến tương đương sẽ được hưởng nguy&ecirc;n mức của loại thẻ bảo hiểm y tế.</li><li>Trường hợp vượt tuyến, người bệnh cần c&oacute; giấy chuyển tuyến từ cơ sở kh&aacute;m chữa bệnh ban đầu.</li><li>Trường hợp cấp cứu, người bệnh c&oacute; thể kh&aacute;m chữa bệnh tại bất k&igrave; cơ sở kh&aacute;m chữa bệnh n&agrave;o v&agrave; được huởng nguy&ecirc;n mức của loại thẻ bảo hiểm y tế.</li></ul><div id="eJOY__extension_root" class="eJOY__extension_root_class" style="all: unset;">&nbsp;</div>'}
                    />
                    <QuestionItem
                        question={'Mức hưởng bảo hiểm y tế ĐÚNG TUYẾN đối với dịch vụ khám chữa bệnh thông thường là như thế nào?'}
                        answer={'<p>Dưới đ&acirc;y l&agrave; quy định về mức hưởng bảo hiểm y tế với trường hợp kh&aacute;m chữa bệnh đ&uacute;ng tuyến theo Luật về Bảo hiểm y tế sửa đổi năm 2014:</p><p>Mức hưởng bảo hiểm y tế 100% chi ph&iacute; kh&aacute;m bệnh, chữa bệnh với người bệnh l&agrave;:</p><ul><li>Sĩ quan, hạ sĩ quan nghiệp vụ v&agrave; sĩ quan, hạ sĩ quan</li><li>Người c&oacute; c&ocirc;ng c&aacute;ch mạng;</li><li>Trẻ em dưới 6 tuổi</li><li>Người bệnh c&oacute; chi ph&iacute; cho 1 lần kh&aacute;m bệnh, chữa bệnh thấp hơn 15% mức lương cơ sở (lương tối thiểu) v&agrave; thực hiện kh&aacute;m bệnh, chữa bệnh tại tuyến x&atilde;</li><li>Người thuộc diện hưởng trợ cấp bảo trợ x&atilde; hội h&agrave;ng th&aacute;ng</li><li>Người thuộc hộ gia đ&igrave;nh ngh&egrave;o</li><li>Người d&acirc;n tộc thiểu số đang sinh sống tại v&ugrave;ng c&oacute; điều kiện kinh tế kh&oacute; khăn, đặc biệt kh&oacute; khăn</li></ul><p>&nbsp;</p><p>95% chi ph&iacute; kh&aacute;m bệnh, chữa bệnh với người bệnh l&agrave;:</p><ul><li>Người đang hưởng lương hưu, trợ cấp mất sức lao động h&agrave;ng th&aacute;ng</li><li>Người thuộc hộ gia đ&igrave;nh cận ngh&egrave;o</li><li>Th&acirc;n nh&acirc;n người c&oacute; c&ocirc;ng với c&aacute;ch mạng</li></ul><p>&nbsp;</p><p>80% chi ph&iacute; kh&aacute;m bệnh, chữa bệnh đối với c&aacute;c trường hợp kh&aacute;c.</p><p>&nbsp;</p><p><strong><em>T&oacute;m lại,</em></strong>&nbsp;đa phần người bệnh được hưởng 80% chi ph&iacute; kh&aacute;m chữa bệnh, trừ trường hợp đặc biệt theo quy định của Luật Bảo hiểm x&atilde; hội.</p><p>&nbsp;</p><p>C&aacute;c giấy tờ cần thiết để được hưởng bảo hiểm y tế:</p><ul><li>Thẻ bảo hiểm y tế</li><li>Giấy tờ t&ugrave;y th&acirc;n hợp lệ: Hộ chiếu, chứng minh thư nh&acirc;n d&acirc;n, giấy khai sinh</li><li>Giấy chuyển viện đ&uacute;ng tuyến - nếu người bệnh kh&aacute;m tại cơ sở y tế kh&ocirc;ng phải cơ sở y tế kh&aacute;m chữa bệnh ban đầu</li></ul><div id="eJOY__extension_root" class="eJOY__extension_root_class" style="all: unset;">&nbsp;</div>'}
                    />
                    <QuestionItem
                        question={'Mức hưởng bảo hiểm y tế ĐÚNG TUYẾN đối với dịch vụ kỹ thuật cao, chi phí lớn là như thế nào?'}
                        answer={'<p>Dưới đ&acirc;y l&agrave; quy định về mức hưởng bảo hiểm y tế với trường hợp kh&aacute;m chữa bệnh đ&uacute;ng tuyến theo Luật về Bảo hiểm y tế sửa đổi năm 2014:</p> <p>&nbsp;</p> <p>Mức hưởng bảo hiểm y tế trường hợp sử dụng dịch vụ kỹ thuật cao, chi ph&iacute; lớn:</p> <p>100% chi ph&iacute; KCB kh&ocirc;ng giới hạn tỷ lệ thanh to&aacute;n đối với:</p> <ul> <li>Trẻ em dưới 6 tuổi</li> <li>Người hoạt động c&aacute;ch mạng trước 1945</li> <li>Người hoạt động c&aacute;ch mạng từ 01/01/1945 đến trước 19/8/1945</li> <li>B&agrave; mẹ Việt Nam anh h&ugrave;ng</li> <li>Thương binh, người hưởng ch&iacute;nh s&aacute;ch như thương binh, thương binh loại B, bệnh binh khi điều trị vết thương, thương tật t&aacute;i ph&aacute;t</li> </ul> <p>100% chi ph&iacute; đối với:</p> <ul> <li>Sĩ quan, hạ sĩ quan nghiệp vụ v&agrave; sĩ quan, hạ sĩ quan chuy&ecirc;n m&ocirc;n kỹ thuật đang c&ocirc;ng t&aacute;c trong lực lượng c&ocirc;ng an nh&acirc;n d&acirc;n nhưng kh&ocirc;ng vượt qu&aacute; 40 th&aacute;ng lương cơ sở (lương tối thiểu chung) cho một lần sử dụng dịch vụ kỹ thuật. Phần c&ograve;n lại do cơ quan, đơn vị quản l&yacute; đối tượng chi trả</li> <li>Người c&oacute; c&ocirc;ng với c&aacute;ch mạng nhưng kh&ocirc;ng vượt qu&aacute; 40 th&aacute;ng lương cơ sở (lương tối thiểu chung) cho một lần sử dụng dịch vụ kỹ thuật quy định tại th&ocirc;ng tư li&ecirc;n tịch số 41/2014/TTLT/BYT-BTC</li> </ul> <p>&nbsp;</p> <p>95%&nbsp; chi ph&iacute; đối với:</p> <ul> <li>Người hưởng lương hưu, trợ cấp BHXH h&agrave;ng th&aacute;ng</li> <li>Th&acirc;n nh&acirc;n người c&oacute; c&ocirc;ng với c&aacute;ch mạng trừ nh&oacute;m đối tượng quy định điểm i khoản 3, điều 12 Luật BHXH số 46/2014</li> <li>Người thuộc hộ gia đ&igrave;nh cận ngh&egrave;o</li> </ul> <p>&nbsp;</p> <p>80% chi ph&iacute; d&agrave;nh cho đối tượng v&agrave; nh&oacute;m đối tượng kh&aacute;c.</p> <p>&nbsp;</p> <p><strong><em>T&oacute;m lại,&nbsp;</em></strong>đa phần người bệnh được hưởng 80% chi ph&iacute; kh&aacute;m, chữa bệnh, trừ trường hợp đặc biệt theo quy định c'}
                    />
                    <QuestionItem
                        question={'Mức hưởng bảo hiểm y tế TRÁI TUYẾN là như thế nào?'}
                        answer={'<div class="faq open"> <div class="faq open"> <div class="faq open"> <p>Theo Luật Bảo hiểm sửa đổi năm 2014, kh&aacute;m chữa bệnh kh&ocirc;ng đ&uacute;ng cơ sở đăng k&yacute; kh&aacute;m chữa bệnh ban đầu hoặc kh&ocirc;ng theo tuyến chuy&ecirc;n m&ocirc;n kỹ thuật (trừ trường hợp cấp cứu) được hưởng mức như sau:</p> <ul> <li>Tại bệnh viện tuyến trung ương l&agrave; 40% của chi ph&iacute; được hưởng khi điều trị nội tr&uacute;.</li> <li>Tại bệnh viện tuyến tỉnh l&agrave; 60% của chi ph&iacute; được hưởng khi điều trị nội tr&uacute; cho đến ng&agrave;y 31 th&aacute;ng 12 năm 2020. Mức hưởng l&agrave; 100% chi ph&iacute; điều trị nội tr&uacute; từ ng&agrave;y 01 th&aacute;ng 01 năm 2021 trong phạm vi cả nước.</li> </ul> <p>Để hưởng bảo hiểm y tế, người bệnh cần mang theo c&aacute;c loại giấy tờ sau:</p> <ul> <li>Thẻ bảo hiểm y tế</li> <li>Giấy tờ t&ugrave;y th&acirc;n hợp lệ: Hộ chiếu, chứng minh thư nh&acirc;n d&acirc;n, giấy khai sinh đối với trẻ em</li> <li>T&oacute;m lại, để được hưởng đầy đủ chế độ bảo hiểm y tế khi đi kh&aacute;m chữa bệnh, người bệnh cần kh&aacute;m chữa v&agrave; thực hiện chuyển đ&uacute;ng tuyến theo quy định.</li> </ul> <p>&nbsp;</p> <p><strong><em>Lưu &yacute;:</em></strong></p> <p>Đối với kh&aacute;m bảo hiểm tại c&aacute;c bệnh viện tuyến tr&ecirc;n: Nhiều người muốn được kh&aacute;m ở bệnh viện tuyến tr&ecirc;n v&agrave; đồng thời được hưởng bảo hiểm. Muốn vậy, cần phải l&agrave;m thủ tục chuyển tuyến v&agrave; sẽ mất nhiều thời gian.</p> <p>Do đ&oacute;, nếu l&agrave; kh&aacute;m bệnh đơn thuần, bạn c&oacute; thể đi kh&aacute;m trước m&agrave; kh&ocirc;ng d&ugrave;ng bảo hiểm y tế. Sau khi c&oacute; kết luận từ b&aacute;c sĩ, bạn c&oacute; thể chuyển tuyến để điều trị nếu cần thiết.</p> <p>Một số lựa chọn khi đi kh&aacute;m:</p> <ul> <li>Đến trực tiếp tại Khoa kh&aacute;m bệnh của bệnh viện c&ocirc;ng</li> <li>Đăng k&iacute; kh&aacute;m với c&aacute;c b&aacute;c sĩ uy t&iacute;n tại Khu kh&aacute;m theo y&ecirc;u cầu của bệnh viện c&ocirc;ng</li> <li>Đăng k&iacute; kh&aacute;m với c&aacute;c b&aacute;c sĩ uy t&iacute;n tại bệnh viện tư nh&acirc;n v&agrave; ph&ograve;ng kh&aacute;m tư nh&acirc;n</li> </ul> <p><em>&nbsp;</em></p> <p><em>Nguồn tham khảo:</em></p> <ul> <li>https://baohiemxahoidientu.vn/bhxh/quyen-loi-huong-the-bhyt-doi-voi-cac-doi-tuong-tham-gia-bhyt.html</li> <li>https://baohiemxahoidientu.vn/bhxh/bhyt-bat-buoc-nhung-dieu-can-biet-khi-kham-chua-benh-bang-the-bhyt.html</li> </ul> </div> </div> </div> <div id="eJOY__extension_root" class="eJOY__extension_root_class" style="all: unset;">&nbsp;</div>'}
                    />
                    <QuestionItem
                        question={'Tôi cần làm những thủ tục gì để được hưởng Bảo hiểm y tế?'}
                        answer={'<div class="faq open"> <div class="faq open"> <div class="faq open"> <p>Bạn cần mang theo c&aacute;c loại giấy tờ sau để được hưởng chế độ bảo hiểm:</p> <ul> <li>Thẻ bảo hiểm y tế</li> <li>Giấy tờ t&ugrave;y th&acirc;n: Chứng minh thư nh&acirc;n d&acirc;n, giấy khai sinh (trẻ em)</li> <li>Giấy chuyển tuyến (nếu kh&aacute;m tr&aacute;i tuyến)</li> </ul> </div> </div> </div> <div id="eJOY__extension_root" class="eJOY__extension_root_class" style="all: unset;">&nbsp;</div>'}
                    />
                    <QuestionItem
                        question={'Bé nhà tôi dưới 6 tuổi nhưng quên mang thẻ Bảo hiểm thì có được hưởng Bảo hiểm cho trẻ dưới 6 tuổi không?'}
                        answer={'<div class="faq open"> <div class="faq open"> <div class="faq open"> <p>C&oacute;. Đối với trẻ em dưới 6 tuổi, b&eacute; cần c&oacute; giấy khai sinh v&agrave; giấy chuyển tuyến (nếu c&oacute;) để được thanh to&aacute;n bảo hiểm như b&igrave;nh thường.</p> <p>Trường hợp phải điều trị ngay sau khi sinh m&agrave; chưa c&oacute; giấy chứng sinh th&igrave; thủ trưởng cơ sở y tế v&agrave; cha hoặc mẹ hoặc người gi&aacute;m hộ của trẻ k&yacute; x&aacute;c nhận v&agrave;o hồ sơ bệnh &aacute;n để l&agrave;m căn cứ thanh to&aacute;n v&agrave; chịu tr&aacute;ch nhiệm về việc x&aacute;c nhận n&agrave;y.</p> <p><em>(Theo Luật Bảo hiểm y tế sửa đổi năm 2014)</em></p> </div> </div> </div> <div id="eJOY__extension_root" class="eJOY__extension_root_class" style="all: unset;">&nbsp;</div>'}
                    />
                    <QuestionItem
                        question={'Tôi chỉ đi khám bình thường thì có được hưởng bải hiểm không hay chỉ khi phẫu thuật hoặc nằm viện thì mới được hưởng BH?'}
                        answer={'<div class="faq open"> <div class="faq open"> <div class="faq open"> <p>Kh&aacute;m thường c&oacute; được hưởng bảo hiểm y tế trong trường hợp kh&aacute;m Đ&Uacute;NG TUYẾN bảo hiểm y tế, tức:&nbsp;</p> <ol> <li>Kh&aacute;m tại cơ sở y tế kh&aacute;m chữa bệnh ban đầu ghi tr&ecirc;n bảo hiểm y tế</li> <li>Kh&aacute;m tại cơ sở y tế kh&aacute;m chữa bệnh ghi tr&ecirc;n giấy chuyển tuyến</li> </ol> <p>Trường hợp kh&aacute;m chữa bệnh tr&aacute;i tuyến bạn chỉ được hưởng bảo hiểm cho chi ph&iacute; điều trị nội tr&uacute;.</p> </div> </div> </div> <div id="eJOY__extension_root" class="eJOY__extension_root_class" style="all: unset;">&nbsp;</div>'}
                    />
                </div>
            </>

        );
    }
}

const mapStateToProps = state => {
    return {
        language: state.app.language,
    };
};

const mapDispatchToProps = dispatch => {
    return {
    };
};

export default connect(mapStateToProps, mapDispatchToProps)(Insurance);
